<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~  Copyright (c) 2020-2026 Remal Software and Arnold SOMOGYI All rights reserved
  ~
  ~  Since:  February 2024
  ~  Author: Arnold SOMOGYI <arnold.somogyi@gmail.com>
  ~
  ~  Description:
  ~     Application POM.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
    </parent>

    <groupId>com.remal.springbox</groupId>
    <artifactId>spring-box</artifactId>
    <version>0.7.1</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.proc>full</maven.compiler.proc>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <hazelcast.version>5.5.0</hazelcast.version>
        <jakarta.servlet-api.version>6.1.0</jakarta.servlet-api.version>
        <kafka-clients.version>4.0.0</kafka-clients.version>
        <logback-classic.version>1.5.18</logback-classic.version>
        <lombok.version>1.18.38</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <micrometer.version>1.14.5</micrometer.version>
        <picocli.version>4.7.6</picocli.version>
        <postgresql.version>42.7.5</postgresql.version>
        <slf4j-api.version>2.0.17</slf4j-api.version>
        <spring-boot.version>3.4.4</spring-boot.version>
        <spring-cloud-starter-consul.version>4.2.1</spring-cloud-starter-consul.version>
        <spring-kafka.version>3.3.4</spring-kafka.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- spring boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-aop</artifactId>
                <version>${spring-boot.version}</version>
                <scope>provided</scope>
            </dependency>
            <!-- spring cloud: hashicorp consul -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-consul-discovery</artifactId>
                <version>${spring-cloud-starter-consul.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-consul-config</artifactId>
                <version>${spring-cloud-starter-consul.version}</version>
            </dependency>
            <!-- spring kafka -->
            <dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka</artifactId>
                <version>${spring-kafka.version}</version>
            </dependency>
            <!-- java's kafka library and its log dependencies: slf4j must be updated -->
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>${kafka-clients.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j-api.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback-classic.version}</version>
            </dependency>
            <!-- remal dependencies -->
            <dependency>
                <groupId>com.remal.springbox</groupId>
                <artifactId>spring-box-commons</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- lombok library -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <!-- application monitoring facade -->
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>${micrometer.version}</version>
            </dependency>
            <!-- Servlet API -->
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet-api.version}</version>
                <scope>provided</scope>
            </dependency>
            <!-- database -->
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
            <!-- mappings between java beans -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <!-- hazelcast cache -->
            <dependency>
                <groupId>com.hazelcast</groupId>
                <artifactId>hazelcast</artifactId>
                <version>${hazelcast.version}</version>
            </dependency>
            <!-- picocli: build rich command line applications  -->
            <dependency>
                <groupId>info.picocli</groupId>
                <artifactId>picocli</artifactId>
                <version>${picocli.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- generate build information + executable JAR -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build-info</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- enable annotation-processors for lombok and mapstruct -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>spring-box-commons</module>
        <module>spring-box-hazelcast-counter</module>
        <module>spring-box-hazelcast-demo</module>
        <module>spring-box-kafka-consumer</module>
        <module>spring-box-kafka-player</module>
        <module>spring-box-kafka-producer</module>
        <module>spring-box-user-service</module>
        <module>spring-box-welcome-service</module>
    </modules>
</project>
