<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>spring-box-hazelcast-demo</artifactId>
	<name>springbox-hazelcast-demo</name>
	<description>Demo project for demonstrating Hazelcast Near-Cache</description>

	<parent>
		<groupId>com.remal.springbox</groupId>
		<artifactId>spring-box</artifactId>
		<version>0.7.1</version>
	</parent>

	<dependencies>
		<!-- hazelcast cache -->
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
		</dependency>
		<!-- lombok library -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>
</project>
