##################################################
# embedded web server
##################################################
server.port=8443
server.ssl.bundle=web-server

##################################################
# spring core
##################################################
spring.application.name=@project.name@
spring.application.version=@project.version@

##################################################
# log configuration
##################################################
logging.file.name=/logs/@project.name@.log
logging.level.org.springframework.context=WARN
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.web=WARN
logging.level.com.remal=DEBUG

##################################################
# customize the jackson object mapper
##################################################
spring.jackson.serialization.indent_output=true

##################################################
# hashicorp consul
##################################################
spring.config.import=consul:
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.instanceId=${spring.application.name}
spring.cloud.consul.discovery.tags=service,${spring.application.version}
spring.cloud.consul.discovery.scheme=https
spring.cloud.consul.discovery.health-check-interval=2s
spring.cloud.consul.discovery.health-check-timeout=2s
spring.cloud.consul.discovery.health-check-critical-timeout=10s
spring.cloud.consul.discovery.query-passing=true
spring.cloud.consul.config.name=com/remal/springbox/@project.name@

##################################################
# application monitoring
##################################################
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.access=unrestricted
management.endpoints.web.exposure.include=info,health,prometheus

##################################################
# spring ssh-bundle configuration
##################################################
# embedded web server
spring.ssl.bundle.jks.web-server.key.alias=${FQDN}
spring.ssl.bundle.jks.web-server.keystore.location=file:/tmp/${FQDN}.p12
spring.ssl.bundle.jks.web-server.keystore.password=changeit
spring.ssl.bundle.jks.web-server.keystore.type=PKCS12

##################################################
# database
##################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/default_db
spring.datasource.username=application
spring.datasource.password=password
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.sql.init.continue-on-error=false
